language: objective-c

before_install:
    # - `xctool`, required to build the unit test and documentation targets
    #   Workaround for https://github.com/travis-ci/travis-ci/issues/2051#issuecomment-40817341
    - brew update
    - gem install cocoapods -v '0.33.1'
    - pod install

xcode_workspace: Snowplow.xcworkspace
xcode_scheme: Snowplow
xcode_sdk:
    - iphonesimulator7.1
    - iphonesimulator7.0
    # - iphonesimulator6.1
    # - iphoneos7.1
    # - iphoneos7.0
    # - iphoneos6.1
